class PitcherProfile:

    def __init__(self, playerId ,Team, ERA, G, CG, SHO, W, L, SV, HLD, WPCT, TBF, NP, IP, H, B2, B3, HR, SAC, SF, BB, IBB, SO, WP, BK, R, ER, BSV, WHIP, AVG, QS):
        self.playerId = playerId #플레이어
        self.Team = Team #소속 팀
        self.ERA = ERA #평균 자책점
        self.G = G #경기
        self.CG = CG #완투
        self.SHO = SHO #셧아웃(완봉)
        self.W = W #승리
        self.L = L #패배
        self.SV = SV #세이브
        self.HLD = HLD #홀드
        self.WPCT = WPCT #승률
        self.TBF = TBF #타자수
        self.NP = NP #투구수
        self.IP = int(IP.split(" ")[0]) #이닝
        self.H = H #피안타
        self.B2 = B2 #2루타
        self.B3 = B3 #3루타
        self.HR = HR #홈런
        self.SAC = SAC #희생번트
        self.SF = SF #희생플라이
        self.BB = BB #볼넷
        self.IBB = IBB #고의사구
        self.SO = SO #삼진
        self.WP = WP #폭투
        self.BK = BK #투수 보크
        self.R = R #실점
        self.ER = ER #자책점
        self.BSV = BSV #블론 세이브
        self.WHIP = WHIP #이닝당 출루허용률
        self.AVG = AVG #피안타율
        self.QS = QS #퀄리티스타트

    def addQuery(self):
        sql = "INSERT INTO PitcherProfiles (playerId ,Team, ERA, G, CG, SHO, W, L, SV, HLD, WPCT, TBF, NP, IP, H, B2, B3, HR, SAC, SF, BB, IBB, SO, WP, BK, R, ER, BSV, WHIP, AVG, QS) VALUES("
        sql += str(self.playerId)+","
        sql += "'" + self.Team +"',"
        sql += str(self.ERA)+","
        sql += str(self.G)+","
        sql += str(self.CG)+","
        sql += str(self.SHO)+","
        sql += str(self.W)+","
        sql += str(self.L)+","
        sql += str(self.SV)+","
        sql += str(self.HLD)+","
        sql += str(self.WPCT)+","
        sql += str(self.TBF)+","
        sql += str(self.NP)+","
        sql += str(self.IP)+","
        sql += str(self.H)+","
        sql += str(self.B2)+","
        sql += str(self.B3)+","
        sql += str(self.HR)+","
        sql += str(self.SAC)+","
        sql += str(self.SF)+","
        sql += str(self.BB)+","
        sql += str(self.IBB)+","
        sql += str(self.SO)+","
        sql += str(self.WP)+","
        sql += str(self.BK)+","
        sql += str(self.R)+","
        sql += str(self.ER)+","
        sql += str(self.BSV)+","
        sql += str(self.WHIP)+","
        sql += str(self.AVG)+","
        sql += str(self.QS)
        sql += ");"
        return sql
